baseURL = 'https://bpms-hub.github.io/recipe-book/'
languageCode = 'en-us'
title = 'Recipe Book'
theme = 'hugo-theme-relearn'
publishDir = 'docs'

[params]
relativeURLs = false
minify = true
themeVariant = 'zen-light'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[author]
  email = 'beepiams@me.com'
  name = 'Beep Iams'

  